#!/usr/bin/env bash
export DOCKER_BUILDKIT=1
export BUILDX_EXPERIMENTAL=1
export BUILDKIT_MULTI_PLATFORM=1
export COMPOSE_EXPERIMENTAL=1
export BUILDKIT_PROGRESS=plain
export DOCKER_CLI_EXPERIMENTAL=enabled
export PROJECT_DEBUG=1
