---
######################################################################
# @Project      : sanctuary
# @File         : docker-compose.yml
# @Description  : Docker Compose configuration for defining and managing
#                 services within the sanctuary project. This file specifically
#                 defines the base service and extends common configurations.
#
# @Author       : Alan Szmyt
# @Date         : 2024-08-23
# @Version      : 1.0
######################################################################

# Common labels for Docker objects
# Documentation: https://docs.docker.com/compose/compose-file/compose-file-v3/#labels
x-labels: &labels
  labels:
    # Name of the application, set using the Compose project name
    # Reference: https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option
    app.name: ${COMPOSE_PROJECT_NAME}

services:
  base:
    # Extends the common service configurations from an external file
    # Documentation: https://docs.docker.com/compose/extends/
    extends:
      file: ../common.yml
      service: common

    # The image name and version for the base service
    # Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/#image
    image: ${COMPOSE_PROJECT_NAME}/${BASE_IMAGE_NAME}:${BASE_IMAGE_VERSION}

    # Hostname for the base service
    # Documentation: https://docs.docker.com/compose/compose-file/compose-file-v3/#hostname
    hostname: ${COMPOSE_PROJECT_NAME}.${BASE_HOSTNAME}

    # Container name for the base service
    # Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name
    container_name: ${COMPOSE_PROJECT_NAME}-${BASE_HOSTNAME}

    # Annotations for the base service
    # Documentation: https://docs.docker.com/compose/compose-file/compose-file-v3/#annotations
    annotations:
      com.docker.compose.service: ${COMPOSE_PROJECT_NAME}-${BASE_HOSTNAME}

    build:
      context: .
      dockerfile: base.Dockerfile
      target: base
      # https://docs.docker.com/reference/cli/docker/buildx/build/#cache-to
      # cache_to:
      #   - type=local,dest=${PROJECT_CACHE_DIR}/.buildx-cache
      # platforms:
      #   - "linux/arm64"
      # - "linux/amd64"

      # Arguments to pass to the build process
      # Reference: https://docs.docker.com/reference/compose-file/build/#args
      args:
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
        DEBIAN_IMAGE_VERSION: bookworm-20240904

    # Environment file containing environment variables for the base service
    # Documentation: https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file
    env_file:
      - base.env
